<script setup>
import formatStuff from "@/utilities/format-stuff";
import { storeToRefs } from "pinia";
import { useAffiliateStore } from "../../stores/affiliate";

const { formattedNumber } = formatStuff();
const { earnings } = storeToRefs(useAffiliateStore());
</script>
<template>
  <div>
    <div
      class="bg-white dark:bg-[#504B5C] relative space-y-2 pt-4 px-4 pb-2 border border-gray-300 dark:border-white/15 mt-3 rounded-3xl overflow-clip"
    >
      <div class="cornertip text-gray-950 text-sm font-bold pl-4 pr-6">
        Commission 1
      </div>

      <div class="text-gray-800 dark:text-slate-300 text-sm">
        Get
        <span class="text-green-500 font-bold">KSH 30</span> instantly for every
        friend you refer and wagers KSH30!
      </div>
      <!-- <div class="text-xs text-gray-600 dark:text-slate-400">
        Today's Progress: 0
      </div> -->
      <div>
        <div class="text-sm font-bold text-slate-800 dark:text-slate-50 w-full">
          KSH
          {{
            formattedNumber(earnings?.earnings?.totalPlayerRegisteredEarnings)
          }}
        </div>
        <div class="text-xs text-gray-600 dark:text-slate-400 w-full">
          Revenue earned
        </div>
      </div>
    </div>
  </div>

  <div>
    <div
      class="bg-white dark:bg-[#504B5C] relative space-y-2 pt-4 px-4 pb-2 border border-gray-300 dark:border-white/15 mt-3 rounded-3xl overflow-clip"
    >
      <div class="cornertip text-gray-950 text-sm font-bold pl-4 pr-6">
        commission 2
      </div>

      <div class="text-gray-800 dark:text-slate-300 text-sm">
        Earn <span class="text-green-500 font-bold">30%</span> commission based
        on the net-positive revenue generated by your referred users.
      </div>
      <!-- <div class="text-xs text-slate-800 dark:text-slate-400">
        Today's Progress: 0
      </div> -->
      <div class="border-t dark:border-white/20">
        <div class="text-sm text-gray-950 dark:text-slate-200 w-full">
          <div
            class="text-sm font-bold text-slate-800 dark:text-slate-50 w-full"
          >
            KSH
            {{
              formattedNumber(earnings?.earnings?.totalPlayerRevenueEarnings)
            }}
          </div>
        </div>
        <div class="text-xs text-slate-800 dark:text-slate-400 w-full">
          Revenue earned
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.cornertip {
  position: absolute;
  top: 0;
  left: 0;

  background: url(/cornertip.png) no-repeat;
  background-size: 100%;
}
</style>
