<script setup>
import { ref } from "vue";

const faqs = ref([
  {
    id: 1,
    question: "How to Earn Through Hakibets Affiliate Program?",
    answer: `Spread the word! Share your link today and start earning commissions from every crash game
bet your referrals make.`,
  },
  {
    id: 2,
    question:
      "What are the requirements for eligibility to participate in this program?",
    answer: `It's completely free with no conditions - just share with others and grow your affiliate network!`,
  },
  {
    id: 3,
    question: "How is Commission calculated?",
    answer: `Earn 30% commission based on the net-positive revenue generated by your referred users.`,
  },
  {
    id: 4,
    question: "Can I lose any money for players that win on the site?",
    answer: `When your players win, you share in their success—but you never lose. Even if overall game profits are negative, your revenue balance resets to zero weekly, ensuring no losses carry over.
Play risk-free, win big!`,
  },
  {
    id: 5,
    question: "How can I see what I can earn?",
    answer: `We have a very simple and clear visual that displays what your current revenue is for the current week, the overall revenue you have generated and lists the players that you have signed up (not any of their personal data, just to confirm that they have successfully registered through you).`,
  },
  {
    id: 6,
    question:
      "When are my weekly earnings finalized and available for withdrawal?",
    answer: `Your weekly earnings as an Hakibets Crash Games Affiliate are calculated from Monday 00:00 EAT to Sunday 23:59 EAT, with the final revenue figure at Sunday’s close determining your payout—regardless of midweek fluctuations. Your first payment will only be locked in after a full calendar week has passed since your first referred player starts playing Crash Games, ensuring a fair and transparent payout schedule.`,
  },
]);

const openAccordion = (id) => {
  faqs.value.forEach((faq) => {
    if (faq.id === id) {
      faq.isOpened = !faq.isOpened;
    } else {
      faq.isOpened = false;
    }
  });
};
</script>

<template>
  <div
    class="border border-gray-300 dark:bg-[#504B5C] dark:border-white/20 rounded-md bg-white p-4 mt-3"
  >
    <div class="pb-3">
      <h4 class="text-3xl font-bold text-center text-amber-500">FAQ's</h4>
    </div>

    <!-- Accordion Item 2 -->
    <div
      v-for="faq in faqs"
      :key="faq.id"
      class="text-white text-sm first:mt-2 flex-col mb-3 border dark:border-dark-purple-17 rounded-3xl overflow-clip"
    >
      <div
        class="flex justify-between dark:text-white items-center p-3 bg-gray-200 dark:bg-[#2E283E]"
        @click="openAccordion(faq.id)"
      >
        <div class="flex space-x-2 items-center">
          <div class="font-medium text-gray-950 dark:text-slate-300">
            {{ faq.question }}
          </div>
        </div>
        <ArrowUpSolid
          v-if="faq.isOpened"
          class="h-5 w-5 text-gray-950 dark:text-white"
        />
        <ArrowRightSolid v-else class="h-5 w-5 text-gray-950 dark:text-white" />
      </div>
      <div v-if="faq.isOpened">
        <div
          class="bg-gray-100 text-md dark:bg-dark-purple-18 flex justify-between text-gray-600 dark:text-slate-400 p-3 text-md items-center"
        >
          <div>{{ faq.answer }}</div>
        </div>
      </div>
    </div>
  </div>
</template>
