import formatStuff from "../utilities/format-stuff";

import { crashGamesRouteName } from "./useCasino";

const { formCloudflareImage } = formatStuff();

const redBaronImg = formCloudflareImage("dca13b16-9130-4d26-95fc-170e8227d800");
const categories = [
  {
    category_id: "",
    category_name: "Flying High",
    cat_binomen: "",
    games_count: "",
  },
  {
    category_id: "popular",
    category_name: "Popular",
    cat_binomen: "popular",
    games_count: "",
  },
  {
    category_id: "justLanded",
    category_name: "Just Landed",
    cat_binomen: "justLanded",
    games_count: "",
  },
  {
    category_id: "Multiplier",
    category_name: "Multiplier",
    cat_binomen: "Multiplier",
    games_count: "",
  },
];

const games = [
  {
    id: 2,
    routeName: crashGamesRouteName,
    gameName: "aviator",
    providerName: "Spribe",
    imgUrl: "/gstatic/games/spribe/aviator.jpg",
    imgFullUrl: "/aviator-banner.webp",
    live: false,
    hot: false,
  },
  {
    id: 2184,
    routeName: crashGamesRouteName,
    gameName: "Red Baron",
    providerName: "Evolution",
    imgUrl: redBaronImg,
    imgFullUrl: redBaronImg,
    live: false,
    hot: false,
  },
  {
    id: 639,
    routeName: crashGamesRouteName,
    gameName: "Aviatrix",
    providerName: "Redgenn",
    imgUrl: "/gstatic/games/redgenn/aviatrix.jpg",
    imgFullUrl: "https://agstatic.com/games/redgenn/aviatrix.jpg",
    live: false,
    hot: false,
  },
  {
    id: 499,
    routeName: crashGamesRouteName,
    gameName: "JetX",
    providerName: "SmartSoft",
    imgUrl: "/gstatic/games/smartsoft/jetx.jpg",
    imgFullUrl: "https://agstatic.com/games/smartsoft/jetx.jpg",
    live: false,
    hot: false,
  },
  {
    id: 1666,
    gameName: "Aviamasters",
    providerName: "BGaming",
    routeName: crashGamesRouteName,
    imgUrl: "https://agstatic.com/games/bgaming/aviamasters.jpg",
    imgFullUrl: "https://agstatic.com/games/bgaming/aviamasters.jpg",
    new: true,
    hot: false,
  },
  {
    id: 1231,
    routeName: crashGamesRouteName,
    gameName: "Aero",
    providerName: "TurboGames",
    imgUrl: "/gstatic/games/turbogames/aero.jpg ",
    imgFullUrl: "https://agstatic.com/games/turbogames/aero.jpg",
    live: false,
    hot: false,
  },

  {
    id: 1223,
    routeName: crashGamesRouteName,
    category_id: "crash",
    gameName: "Maestro",
    providerName: "DigitainCG",
    imgUrl: "/gstatic/games/digitaincg/maestro.jpg",
    imgFullUrl: "https://agstatic.com/games/digitaincg/maestro.jpg",
    live: false,
    hot: false,
  },
  {
    id: 1155,
    routeName: crashGamesRouteName,
    category_id: "crash",
    gameName: "Crash Royale",
    providerName: "iMoon",
    imgUrl: "/gstatic/games/imoon/crash_royale.jpg",
    imgFullUrl: "https://agstatic.com/games/imoon/crash_royale.jpg",
    live: false,
    hot: false,
  },
  {
    id: 1232,
    routeName: crashGamesRouteName,
    gameName: "CrashX",
    providerName: "TurboGames",
    imgUrl: "/gstatic/games/turbogames/crashx.jpg ",
    imgFullUrl: "https://agstatic.com/games/turbogames/crashx.jpg",
    live: false,
    hot: false,
  },
  {
    id: 1224,
    routeName: crashGamesRouteName,
    gameName: "MultiHot5",
    category_id: "crash",
    providerName: "SmartSoft",
    imgUrl: "/gstatic/games/smartsoft/multi_hot_ways.jpg",
    imgFullUrl: "https://agstatic.com/games/smartsoft/multi_hot_5.jpg",
    live: false,
    hot: false,
  },
  {
    id: 1162,
    routeName: crashGamesRouteName,
    category_id: "crash",
    gameName: "Crash 1917",
    providerName: "iMoon",
    imgUrl: "/gstatic/games/imoon/crash_1917.jpg",
    imgFullUrl: "https://agstatic.com/games/imoon/crash_1917.jpg",
    live: false,
    hot: false,
  },
  {
    id: 1225,
    routeName: crashGamesRouteName,
    gameName: "PlinkoX",
    category_id: "crash",
    providerName: "SmartSoft",
    imgUrl: "/gstatic/games/smartsoft/plinko_x.jpg",
    imgFullUrl: "https://agstatic.com/games/smartsoft/plinko_x.jpg",
    live: false,
    hot: false,
  },
  {
    id: 1233,
    routeName: crashGamesRouteName,
    gameName: "iMoon Crash",
    providerName: "iMoon",
    imgUrl: "/gstatic/games/imoon/imoon_crash.jpg",
    imgFullUrl: "https://agstatic.com/games/imoon/imoon_crash.jpg",
    live: false,
    hot: false,
  },
  {
    id: 421,
    routeName: crashGamesRouteName,
    gameName: "Space XY",
    providerName: "BGaming",
    imgUrl: "/gstatic/games/bgaming/space_xy.jpg",
    imgFullUrl: "https://agstatic.com/games/bgaming/space_xy.jpg",
    live: false,
    hot: false,
  },

//   {
//     id: 1227,
//     routeName: crashGamesRouteName,
//     gameName: "JetX3",
//     providerName: "SmartSoft",
//     imgUrl: "/gstatic/games/smartsoft/avia_star.jpg",
//     imgFullUrl: "https://agstatic.com/games/smartsoft/avia_star.jpg",
//     live: false,
//     hot: false,
//   },

  {
    id: 552,
    routeName: crashGamesRouteName,
    gameName: "Football X",
    providerName: "SmartSoft",
    imgUrl: "/gstatic/games/smartsoft/football_x.jpg",
    imgFullUrl: "https://agstatic.com/games/smartsoft/football_x.jpg",
    live: false,
    hot: false,
  },

  {
    id: 488,
    routeName: crashGamesRouteName,
    gameName: "Balloon",
    providerName: "SmartSoft",
    imgUrl: "/gstatic/games/smartsoft/balloon.jpg",
    imgFullUrl: "https://agstatic.com/games/smartsoft/balloon.jpg",
    live: false,
    hot: false,
  },

  {
    id: 562,
    routeName: crashGamesRouteName,
    gameName: "Crashout Fireworks",
    providerName: "OneXTwoNetwork",
    imgUrl: "/gstatic/games/onextwonetwork/crashout_fireworks.jpg",
    imgFullUrl:
      "https://agstatic.com/games/onextwonetwork/crashout_fireworks.jpg",
    live: false,
    hot: false,
  },

  {
    id: 620,
    routeName: crashGamesRouteName,
    gameName: "Limbo XY",
    providerName: "BGaming",
    imgUrl: "/gstatic/games/bgaming/limbo_xy.jpg",
    imgFullUrl: "https://agstatic.com/games/bgaming/limbo_xy.jpg",
    live: false,
    hot: false,
  },
  {
    id: 626,
    routeName: crashGamesRouteName,
    gameName: "TowerX",
    providerName: "SmartSoft",
    imgUrl: "/gstatic/games/smartsoft/towerx.jpg",
    imgFullUrl: "https://agstatic.com/games/smartsoft/towerx.jpg",
    live: false,
    hot: false,
  },
  {
    id: 653,
    routeName: crashGamesRouteName,
    gameName: "Gift X",
    providerName: "BGaming",
    imgUrl: "/gstatic/games/bgaming/gift_x.jpg",
    imgFullUrl: "https://agstatic.com/games/bgaming/gift_x.jpg",
    live: false,
    hot: false,
  },

  {
    id: 695,
    routeName: crashGamesRouteName,
    gameName: "Dragon’s Crash",
    providerName: "BGaming",
    imgUrl: "/gstatic/games/bgaming/dragons_crash.jpg",
    imgFullUrl: "https://agstatic.com/games/bgaming/dragons_crash.jpg",
    live: false,
    hot: false,
  },
];

export function useCrash() {
  return {
    categories,
    games,
  };
}
