import {
  casinoGamesRouteName,
  crashGamesRouteName,
  virtualGamesRouteName,
} from "./useCasino";

const hakiLeagueGameId = import.meta.env.VITE_HAKI_LEAGUE_GAME_ID;
const hakiJackpotGameId = import.meta.env.VITE_KIRON_JACKPOT_GAME_ID;

const categories = [
  {
    category_id: "all",
    category_name: "All Games",
    cat_binomen: "all",
    games_count: "",
  },
  {
    category_id: "crash",
    category_name: "Crash",
    cat_binomen: "crash",
    games_count: "",
  },
  {
    category_id: "virtuals",
    category_name: "Virtuals",
    cat_binomen: "virtuals",
    games_count: "",
  },
  //   {
  //     category_id: "slots",
  //     category_name: "Slots",
  //     cat_binomen: "slots",
  //     games_count: "",
  //   },
  {
    category_id: "spins",
    category_name: "Spins",
    cat_binomen: "spins",
    games_count: "",
  },
];

const providers = [
  {
    category_id: "iMoon",
    category_name: "iMoon",
  },
  {
    category_id: "GoldenRace",
    category_name: "GoldenRace ",
  },
  //   {
  //     category_id: "kiron",
  //     category_name: "kiron",
  //   },
];

export function usePopular() {
  const games = [
    {
      id: 2,
      routeName: crashGamesRouteName,
      gameName: "aviator",
      category_id: "crash",
      providerName: "Spribe",
      imgUrl: "/aviator.webp",
      imgFullUrl: "/aviator.webp",
      live: false,
      hot: false,
    },
    //   {
    //     id: 1157,
    //     category_id: "crash",
    //     gameName: "Trade Blazer",
    //     providerName: "iMoon",
    //     imgUrl: "/gstatic/games/imoon/trade_blazer.jpg",
    //     imgFullUrl: "https://agstatic.com/games/imoon/trade_blazer.jpg",
    //     live: false,
    //     hot: false,
    //   },

    {
      id: 639,
      routeName: crashGamesRouteName,
      gameName: "Aviatrix",
      category_id: "crash",
      providerName: "Redgenn",
      imgUrl: "/gstatic/games/redgenn/aviatrix.jpg",
      imgFullUrl: "https://agstatic.com/games/redgenn/aviatrix.jpg",
      live: false,
      hot: false,
    },
    {
      id: 1231,
      routeName: crashGamesRouteName,
      gameName: "Aero",
      category_id: "crash",
      providerName: "TurboGames",
      imgUrl: "/gstatic/games/turbogames/aero.jpg ",
      imgFullUrl: "https://agstatic.com/games/turbogames/aero.jpg",
      live: false,
      hot: false,
    },
    {
      id: 1232,
      routeName: crashGamesRouteName,
      gameName: "CrashX",
      category_id: "crash",
      providerName: "TurboGames",
      imgUrl: "/gstatic/games/turbogames/crashx.jpg ",
      imgFullUrl: "https://agstatic.com/games/turbogames/crashx.jpg",
      live: false,
      hot: false,
    },
    // {
    //   id: 1230,
    //   gameName: "High Flyer",
    //   providerName: "Pragmatic Play",
    //   category_id: "crash",
    //   imgUrl: "/gstatic/games/pragmaticplay/high_flyer.jpg",
    //   imgFullUrl: "https://agstatic.com/games/pragmaticplay/high_flyer.jpg",
    //   live: false,
    //   hot: false,
    // },
    {
      id: hakiLeagueGameId,
      routeName: virtualGamesRouteName,
      gameName: "Haki League",
      category_id: "virtuals",
      providerName: "Kiron",
      imgUrl: "/haki-league.webp",
      imgFullUrl: "/haki-league.webp",
    },
    {
      id: 552,
      routeName: crashGamesRouteName,
      gameName: "Football X",
      providerName: "SmartSoft",
      imgUrl: "/gstatic/games/smartsoft/football_x.jpg",
      imgFullUrl: "https://agstatic.com/games/smartsoft/football_x.jpg",
      live: false,
      hot: false,
    },
    // {
    //   gameName: "Haki Turbo",
    //   category_id: "virtuals",
    //   providerName: "Kiron",
    //   imgUrl: "/haki-turbo.png",
    //   imgFullUrl: "/haki-turbo.png",
    // },
    {
      id: hakiJackpotGameId,
      routeName: virtualGamesRouteName,
      gameName: "Haki Jackpot",
      category_id: "virtuals",
      providerName: "Kiron",
      imgUrl: "/haki-jackpot.webp",
      imgFullUrl: "/haki-jackpot.webp",
    },

    //   {
    //     id: 1155,
    //     category_id: "crash",
    //     gameName: "Crash Royale",
    //     providerName: "iMoon",
    //     imgUrl: "/gstatic/games/imoon/crash_royale.jpg",
    //     imgFullUrl: "https://agstatic.com/games/imoon/crash_royale.jpg",
    //     live: false,
    //     hot: false,
    //   },

    {
      id: 499,
      routeName: crashGamesRouteName,
      gameName: "JetX",
      category_id: "crash",
      providerName: "SmartSoft",
      imgUrl: "/gstatic/games/smartsoft/jetx.jpg",
      imgFullUrl: "https://agstatic.com/games/smartsoft/jetx.jpg",
      live: false,
      hot: false,
    },
    //   {
    //     id: 1162,
    //     category_id: "crash",
    //     gameName: "Crash 1917 ",
    //     providerName: "iMoon",
    //     imgUrl: "/gstatic/games/imoon/crash_1917.jpg",
    //     imgFullUrl: "https://agstatic.com/games/imoon/crash_1917.jpg",
    //     live: false,
    //     hot: false,
    //   },
    {
      id: 1216,
      routeName: casinoGamesRouteName,
      category_id: "spins",
      gameName: "Spin 2 Win",
      providerName: "GoldenRace",
      imgUrl: "/gstatic/games/goldenrace/spin_2_win.jpg",
      imgFullUrl: "https://agstatic.com/games/goldenrace/spin_2_win.jpg  ",
      live: false,
      hot: false,
    },
    {
      id: 1207,
      routeName: virtualGamesRouteName,
      category_id: "virtuals",
      gameName: "England League",
      providerName: "GoldenRace",
      imgUrl: "/ie.webp",
      imgFullUrl: "/ie.webp",
      live: false,
      hot: false,
    },
    {
      id: 1223,
      routeName: crashGamesRouteName,
      category_id: "crash",
      gameName: "Maestro",
      providerName: "DigitainCG",
      imgUrl: "/gstatic/games/digitaincg/maestro.jpg",
      imgFullUrl: "https://agstatic.com/games/digitaincg/maestro.jpg",
      live: false,
      hot: false,
    },
    {
      id: 1162,
      routeName: crashGamesRouteName,
      category_id: "crash",
      gameName: "Crash 1917 ",
      providerName: "iMoon",
      imgUrl: "/gstatic/games/imoon/crash_1917.jpg",
      imgFullUrl: "https://agstatic.com/games/imoon/crash_1917.jpg",
      live: false,
      hot: false,
    },
    {
      id: 1206,
      routeName: virtualGamesRouteName,
      category_id: "virtuals",
      gameName: "Italy League",
      providerName: "GoldenRace",
      imgUrl: "/gstatic/games/goldenrace/italy_league.jpg ",
      imgFullUrl: "/instant-italian.webp",
      live: false,
      hot: false,
    },
    {
      id: 1204,
      routeName: virtualGamesRouteName,
      category_id: "virtuals",
      gameName: " Spain League",
      providerName: "GoldenRace",
      imgUrl: "/isl.webp",
      imgFullUrl: "/isl.webp",
      live: false,
      hot: false,
    },
    {
      id: 1221,
      routeName: virtualGamesRouteName,
      category_id: "virtuals",
      gameName: "Instant Sports",
      providerName: "GoldenRace",
      imgUrl: "/gstatic/games/goldenrace/instant_sports.jpg",
      imgFullUrl: "https://agstatic.com/games/goldenrace/instant_sports.jpg",
      live: false,
      hot: false,
    },
    {
      id: 1193,
      routeName: virtualGamesRouteName,
      category_id: "virtuals",
      gameName: "Germany League",
      providerName: "GoldenRace",
      imgUrl: "/gstatic/games/goldenrace/germany_league.jpg ",
      imgFullUrl: "https://agstatic.com/games/goldenrace/germany_league.jpg",
      live: false,
      hot: false,
    },
  ];

  const newGames = [
    {
      id: 1224,
      routeName: casinoGamesRouteName,
      gameName: "MultiHot5",
      providerName: "SmartSoft",
      imgUrl: "/gstatic/games/smartsoft/multi_hot_ways.jpg",
      imgFullUrl: "https://agstatic.com/games/smartsoft/multi_hot_5.jpg",
      live: false,
      hot: false,
    },
    {
      id: 1228,
      routeName: casinoGamesRouteName,
      gameName: "Sweet Bonanza",
      providerName: "Pragmatic Play",
      imgUrl: "/gstatic/games/pragmaticplay/sweet_bonanza.jpg",
      imgFullUrl: "https://agstatic.com/games/pragmaticplay/sweet_bonanza.jpg",
      live: false,
      hot: false,
    },
    {
      id: 1225,
      routeName: casinoGamesRouteName,
      gameName: "PlinkoX",
      providerName: "SmartSoft",
      imgUrl: "/gstatic/games/smartsoft/plinko_x.jpg",
      imgFullUrl: "https://agstatic.com/games/smartsoft/plinko_x.jpg",
      live: false,
      hot: false,
    },
    {
      id: 1226,
      routeName: casinoGamesRouteName,
      gameName: "Congo Cash",
      providerName: "Pragmatic Play",
      imgUrl: "/gstatic/games/pragmaticplay/congo_cash.jpg",
      imgFullUrl: "https://agstatic.com/games/pragmaticplay/congo_cash.jpg",
      live: false,
      hot: false,
    },
    // {
    //   id: 1227,
    //   routeName: casinoGamesRouteName,
    //   gameName: "JetX3",
    //   providerName: "SmartSoft",
    //   imgUrl: "/gstatic/games/smartsoft/avia_star.jpg",
    //   imgFullUrl: "https://agstatic.com/games/smartsoft/avia_star.jpg",
    //   live: false,
    //   hot: false,
    // },

    {
      id: 1229,
      routeName: casinoGamesRouteName,
      gameName: "Chests of Cai Shen",
      providerName: "Pragmatic Play",
      imgUrl: "/gstatic/games/pragmaticplay/chests_of_cai_shen.jpg",
      imgFullUrl:
        "https://agstatic.com/games/pragmaticplay/chests_of_cai_shen.jpg",
      live: false,
      hot: false,
    },
  ];

  const allGames = [
    {
      id: 310,
      routeName: casinoGamesRouteName,
      gameName: "Fire Strike 2",
      providerName: "Pragmatic Play",
      imgUrl: "/gstatic/games/pragmaticplay/fire_strike_2.jpg",
      imgFullUrl: "https://agstatic.com/games/pragmaticplay/fire_strike_2.jpg",
      live: false,
      hot: false,
    },
    {
      id: 1029,
      routeName: casinoGamesRouteName,
      gameName: "Aztec Gems",
      providerName: "Pragmatic Play",
      imgUrl: "/gstatic/games/pragmaticplay/vs5aztecgems.jpg",
      imgFullUrl: "https://agstatic.com/games/pragmaticplay/vs5aztecgems.jpg",
      live: false,
      hot: false,
    },

    {
      id: 950,
      routeName: casinoGamesRouteName,
      gameName: "Chilli Heat",
      providerName: "Pragmatic Play",
      imgUrl: "/gstatic/games/pragmaticplay/vs25chilli.jpg",
      imgFullUrl: "https://agstatic.com/games/pragmaticplay/vs25chilli.jpg",
      live: false,
      hot: false,
    },

    {
      id: 966,
      routeName: casinoGamesRouteName,
      gameName: "Wild Spells",
      providerName: "Pragmatic Play",
      imgUrl: "/gstatic/games/pragmaticplay/vs25wildspells.jpg",
      imgFullUrl: "https://agstatic.com/games/pragmaticplay/vs25wildspells.jpg",
      live: false,
      hot: false,
    },

    // {
    //   id: 2129,
    //   gameName: "Stock Market",
    //   providerName: "Evolution",
    //   imgUrl: "/gstatic/games/evosw/stock_market.jpg",
    //   imgFullUrl: "https://agstatic.com/games/evosw/stock_market.jpg",
    //   live: false,
    //   hot: false,
    // },

    {
      id: 604,
      routeName: casinoGamesRouteName,
      gameName: "Burning Chilli X",
      providerName: "BGaming",
      imgUrl: "/gstatic/games/bgaming/burning_chilli_x.jpg",
      imgFullUrl: "https://agstatic.com/games/bgaming/burning_chilli_x.jpg",
      live: false,
      hot: false,
    },

    {
      id: 1995,
      routeName: casinoGamesRouteName,
      gameName: "HiLo",
      providerName: "TurboGames",
      imgUrl: "/gstatic/games/turbogames/hilo.jpg",
      imgFullUrl: "https://agstatic.com/games/turbogames/hilo.jpg",
      live: false,
      hot: false,
    },

    {
      id: 275,
      routeName: casinoGamesRouteName,
      gameName: "5 Lions Megaways",
      providerName: "Pragmatic Play",
      imgUrl: "/gstatic/games/turbogames/hilo.jpg",
      imgFullUrl:
        "https://agstatic.com/games/pragmaticplay/5_lions_megaways.jpg",
      live: false,
      hot: false,
    },

    {
      id: 833,
      routeName: casinoGamesRouteName,
      gameName: "Wolf Gold",
      providerName: "Pragmatic Play",
      imgUrl: "//gstatic/games/pragmaticplay/vs25wolfgold.jpg",
      imgFullUrl: "https://agstatic.com/games/pragmaticplay/vs25wolfgold.jpg",
      live: false,
      hot: false,
    },

    // {
    //   id: 1015,
    //   gameName: "888 Gold",
    //   providerName: "Pragmatic Play",
    //   imgUrl: "/gstatic/games/pragmaticplay/cs5triple8gold.jpg",
    //   imgFullUrl: "https://agstatic.com/games/pragmaticplay/cs5triple8gold.jpg",
    //   live: false,
    //   hot: false,
    // },

    {
      id: 964,
      routeName: casinoGamesRouteName,
      gameName: "Hot Safari",
      providerName: "Pragmatic Play",
      imgUrl: "/gstatic/games/pragmaticplay/vs25safari.jpg",
      imgFullUrl: "https://agstatic.com/games/pragmaticplay/vs25safari.jpg",
      live: false,
      hot: false,
    },

    {
      id: 484,
      routeName: casinoGamesRouteName,
      gameName: "Big Bass Crash",
      providerName: "Pragmatic Play Live",
      imgUrl: "/gstatic/games/pragmaticplaylive/big_bass_crash.jpg",
      imgFullUrl:
        "https://agstatic.com/games/pragmaticplaylive/big_bass_crash.jpg",
      live: false,
      hot: false,
    },

    {
      id: 2164,
      routeName: casinoGamesRouteName,
      gameName: "2 Hand Casino Hold'em",
      providerName: "Evolution",
      imgUrl: "/gstatic/games/evosw/2_hand_casino_holdem.jpg",
      imgFullUrl: "https://agstatic.com/games/evosw/2_hand_casino_holdem.jpg",
      live: false,
      hot: false,
    },

    {
      id: 1950,
      routeName: casinoGamesRouteName,
      gameName: "Evolution",
      providerName: "Evolution",
      imgUrl: "/gstatic/games/evosw/top_games.jpg",
      imgFullUrl: "https://agstatic.com/games/evosw/top_games.jpg",
      live: false,
      hot: false,
    },
    {
      id: 1224,
      routeName: casinoGamesRouteName,
      gameName: "MultiHot5",
      providerName: "SmartSoft",
      imgUrl: "/gstatic/games/smartsoft/multi_hot_ways.jpg",
      imgFullUrl: "https://agstatic.com/games/smartsoft/multi_hot_5.jpg",
      live: false,
      hot: false,
    },
    {
      id: 1228,
      routeName: casinoGamesRouteName,
      gameName: "Sweet Bonanza",
      providerName: "Pragmatic Play",
      imgUrl: "/gstatic/games/pragmaticplay/sweet_bonanza.jpg",
      imgFullUrl: "https://agstatic.com/games/pragmaticplay/sweet_bonanza.jpg",
      live: false,
      hot: false,
    },
    {
      id: 1225,
      routeName: casinoGamesRouteName,
      gameName: "PlinkoX",
      providerName: "SmartSoft",
      imgUrl: "/gstatic/games/smartsoft/plinko_x.jpg",
      imgFullUrl: "https://agstatic.com/games/smartsoft/plinko_x.jpg",
      live: false,
      hot: false,
    },
    {
      id: 1226,
      routeName: casinoGamesRouteName,
      gameName: "Congo Cash",
      providerName: "Pragmatic Play",
      imgUrl: "/gstatic/games/pragmaticplay/congo_cash.jpg",
      imgFullUrl: "https://agstatic.com/games/pragmaticplay/congo_cash.jpg",
      live: false,
      hot: false,
    },

    {
      id: 1229,
      routeName: casinoGamesRouteName,
      gameName: "Chests of Cai Shen",
      providerName: "Pragmatic Play",
      imgUrl: "/gstatic/games/pragmaticplay/chests_of_cai_shen.jpg",
      imgFullUrl:
        "https://agstatic.com/games/pragmaticplay/chests_of_cai_shen.jpg",
      live: false,
      hot: false,
    },

    {
      id: 1216,
      routeName: casinoGamesRouteName,
      category_id: "spins",
      gameName: "Spin 2 Win",
      providerName: "GoldenRace",
      imgUrl: "/gstatic/games/goldenrace/spin_2_win.jpg",
      imgFullUrl: "https://agstatic.com/games/goldenrace/spin_2_win.jpg  ",
      live: false,
      hot: false,
    },
  ];

  return {
    games,
    allGames,
    newGames,
    categories,
    providers,
  };
}
