import { virtualGamesRouteName } from "./useCasino";
const categories = [
  {
    category_id: "",
    category_name: "Hot",
    cat_binomen: "",
    games_count: "",
  },
  {
    category_id: "popular",
    category_name: "Popular",
    cat_binomen: "popular",
    games_count: "",
  },
  {
    category_id: "justLanded",
    category_name: "Just Landed",
    cat_binomen: "justLanded",
    games_count: "",
  },
  {
    category_id: "Multiplier",
    category_name: "Multiplier",
    cat_binomen: "Multiplier",
    games_count: "",
  },
];
const games = [
  {
    id: 1207,
    routeName: virtualGamesRouteName,
    category_id: "virtuals",
    gameName: "England League",
    providerName: "GoldenRace",
    imgUrl: "/english.webp",
    imgFullUrl: "/english.webp",
    live: false,
    hot: false,
  },
  {
    id: 1206,
    routeName: virtualGamesRouteName,
    category_id: "virtuals",
    gameName: "Italy League",
    providerName: "GoldenRace",
    imgUrl: "/gstatic/games/goldenrace/italy_league.jpg ",
    imgFullUrl: "/instant-italian.webp",
    live: false,
    hot: false,
  },
  {
    id: 1204,
    routeName: virtualGamesRouteName,
    category_id: "virtuals",
    gameName: "Spain League",
    providerName: "GoldenRace",
    imgUrl: "/isl.webp",
    imgFullUrl: "/isl.webp",
    live: false,
    hot: false,
  },
  {
    id: 1221,
    routeName: virtualGamesRouteName,
    category_id: "virtuals",
    gameName: "Instant Sports",
    providerName: "GoldenRace",
    imgUrl: "/gstatic/games/goldenrace/instant_sports.jpg",
    imgFullUrl: "https://agstatic.com/games/goldenrace/instant_sports.jpg",
    live: false,
    hot: false,
  },
  {
    id: 1193,
    routeName: virtualGamesRouteName,
    category_id: "virtuals",
    gameName: "Germany League",
    providerName: "GoldenRace",
    imgUrl: "/gstatic/games/goldenrace/germany_league.jpg ",
    imgFullUrl: "https://agstatic.com/games/goldenrace/germany_league.jpg",
    live: false,
    hot: false,
  },
  {
    id: 986,
    routeName: virtualGamesRouteName,
    gameName: "Virtual Soccer",
    providerName: "OneXTwoNetwork",
    imgUrl: "/gstatic/games/onextwonetwork/virtual_soccer.jpg",
    imgFullUrl: "virtual.webp",
    live: false,
    hot: false,
  },
  {
    id: 985,
    routeName: virtualGamesRouteName,
    gameName: "Virtual Football Pro",
    providerName: "OneXTwoNetwork",
    imgUrl: "/gstatic/games/onextwonetwork/virtual_football.jpg",
    imgFullUrl:
      "https://agstatic.com/games/onextwonetwork/virtual_football.jpg",
    live: false,
    hot: false,
  },
  //   {
  //     id: 411,
  //     gameName: "iGoal – Football Spanish",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/igoal_football_spanish.jpg",
  //     imgFullUrl: "https://agstatic.com/games/kiron/igoal_football_spanish.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 412,
  //     gameName: "iGoal – Football Italian",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/igoal_football_italian.jpg",
  //     imgFullUrl: "https://agstatic.com/games/kiron/igoal_football_italian.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 430,
  //     gameName: "iGoal – Football English",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/igoal_football_english.jpg",
  //     imgFullUrl: "https://agstatic.com/games/kiron/igoal_football_english.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 556,
  //     gameName: "World Cup Tournament",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/world_cup_tournament.jpg",
  //     imgFullUrl: "https://agstatic.com/games/kiron/world_cup_tournament.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 813,
  //     gameName: "Italian FastLeague Football Match",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/italian_fast_league_football_match.jpg",
  //     imgFullUrl:
  //       "https://agstatic.com/games/kiron/italian_fast_league_football_match.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 814,
  //     gameName: "Spanish FastLeague Football Match",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/spanish_fast_league_football_match.jpg",
  //     imgFullUrl:
  //       "https://agstatic.com/games/kiron/spanish_fast_league_football_match.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 815,
  //     gameName: "English Fast League Football Match",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/english_fast_league_football_match.jpg",
  //     imgFullUrl:
  //       "https://agstatic.com/games/kiron/english_fast_league_football_match.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 816,
  //     gameName: "Golf",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/golf.jpg",
  //     imgFullUrl: "https://agstatic.com/games/kiron/golf.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 817,
  //     gameName: "Football Hub",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/football_hub.jpg",
  //     imgFullUrl: "https://agstatic.com/games/kiron/football_hub.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 818,
  //     gameName: "Steeple Chase",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/steeple_chase.jpg",
  //     imgFullUrl: "https://agstatic.com/games/kiron/steeple_chase.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 924,
  //     gameName: "Italian FastLeague Football Single",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/italian_fast_league.jpg",
  //     imgFullUrl: "https://agstatic.com/games/kiron/italian_fast_league.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 925,
  //     gameName: "Spanish FastLeague Football Single",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/spanish_fast_league.jpg",
  //     imgFullUrl: "https://agstatic.com/games/kiron/spanish_fast_league.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 971,
  //     gameName: "English Fast League Football Single Match",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/fast_footbal.jpg",
  //     imgFullUrl: "https://agstatic.com/games/kiron/fast_footbal.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 972,
  //     gameName: "Hounds",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/platinum_hounds.jpg",
  //     imgFullUrl: "https://agstatic.com/games/kiron/platinum_hounds.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 973,
  //     gameName: "Horses",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/dashing_derby.jpg",
  //     imgFullUrl: "https://agstatic.com/games/kiron/dashing_derby.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 974,
  //     gameName: "Motor racing",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/maxcar_motorracing.jpg",
  //     imgFullUrl: "https://agstatic.com/games/kiron/maxcar_motorracing.jpg",
  //     live: false,
  //     hot: false,
  //   },
  //   {
  //     id: 975,
  //     gameName: "Table tennis",
  //     providerName: "Kiron",
  //     imgUrl: "/gstatic/games/kiron/pro_pong.jpg",
  //     imgFullUrl: "https://agstatic.com/games/kiron/pro_pong.jpg",
  //     live: false,
  //     hot: false,
  //   },
];
export function useVirtual() {
  return {
    games,
    categories,
  };
}
