apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hakibets-ui.fullname" . }}
  labels:
    {{- include "hakibets-ui.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
